# Generated by Django 5.0.4 on 2024-05-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_subcategory_bannerimage_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
