# Generated by Django 5.0.4 on 2024-05-13 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_variant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
